#+options: toc:nil
#+TITLE: About Me
Hi, I'm semi. I'm a programmer who mostly works in keyboard layout
analysis and creation.
** Stuff I have done
*** [[file:semimak/index.org][Semimak]]
    Semimak is a keyboard layout designed primarily for high comfort at
    high typing speeds. In July 2021, [[https://github.com/notgate][NotGate]] and I held a one month
    long tournament to learn it with an $835 prize pool, which over 200
    people participated in.
*** [[./genkey/index.html][genkey]]
    genkey is a tool for keyboard layout analysis and generation that
    I created to make Semimak. It's multi-threaded and pretty
    powerful; on my laptop, it can analyze some simple stats at a rate
    of 1 million layouts per second.
*** klcord
    [[https://github.com/semilin/klcord][klcord]] is a basic Discord bot for getting keyboard layout
    information, because there are too many of them and we can't keep
    track of them or where to find them.

    Usage: =!layout layoutname=
*** More in the future
    I have a lot of ideas. Sometimes I forget them, or am too bad to
    make them. Eventually, some of them will get made, so look forward
    to that.
** Stuff I use
   This changes worryingly frequently so it may not be up to date. 
**** OS
     [[https://voidlinux.org/][Void Linux]] ([[https://github.com/semilin/dots][dots]]).
**** Window Manager
     [[https://github.com/baskerville/bspwm][BSPWM]] ([[https://github.com/semilin/dots/blob/main/bspwm/bspwmrc][config]]).
**** Editor
     [[https://www.gnu.org/software/emacs/][Emacs]] ([[https://github.com/semilin/dotemacs][config]]).
**** Keyboard
     [[https://boardsource.xyz/store/5f2e7e4a2902de7151494f92][BoardSource Microdox]].
**** Layout
     [[file:semimak/index.org::*'r and 'll][Semimak JQ]], my personal mod of Semimak.
     In the past, I have used (higher = more recent):
     + Semimak
     + [[https://notgate.github.io/layout/][ISRT]]
     + [[https://colemakmods.github.io/mod-dh/][Colemak DH]]
** Contact Information
   + Email: [[mailto:semilinares@pm.me][semilinares@pm.me]]
   + [[https://matrix.org/][Matrix]]: =@semilin0:matrix.org=
   + Discord: =semi#5753=
   + [[https://getsession.org/][Session]]: =05d026a337fe782d2a0ef5fe172fa5634f0291ed2bdf0d98025e11d5542ee2c613=

