#+TITLE:Semimak

The Semimak layout is designed to have low finger movement rate -
decreasing the overall speed at which your fingers must travel to type
on average. This doesn’t only mean to optimize for reducing
same-finger bigrams (e.g =ed= on QWERTY), but disjointeds as well
(e.g the =m_y= in =may= on QWERTY). Semimak was the pioneer of DSFB
and weighted finger dexterity.

* Reflecting on Semimak, 3 months later
  On July 1st, 12:00 P.M PDT, Semimak was released. [[https://github.com/notgate][NotGate]] and I held
  a tournament with an $850 prize pool, and over 200 people
  participated in it (including me, just for fun). I got a lot of
  feedback from this! 

** Problems
 
**** Right Index Finger
     Despite the relatively low usage of the right index finger, some
     people had difficulty with it. It is the finger with the highest
     unweighted movement, but that's difficult to avoid, considering
     the index fingers have double the responsibility of a normal
     finger. 

**** Ring Finger Movements
     This seemed to be the biggest issue people had with the layout
     overall. =lr'= and =oa.= columns will cause a lot of movement,
     and the ring fingers are either the slowest or second slowest
     fingers for people.

     This highlights a very interesting effect of
     relative dexterity. I personally never had any issue with it,
     which is unsurprising considering I made the layout adapted to my
     own finger speed. I believed at the time that people could adapt
     to comfort with this, like I was able to with my pinkies.
     However, although almost everyone was able to adapt comfortably
     to the pinky movement, a not insignificant amount of people
     struggled with the ring fingers.

     I now believe that I am simply lucky to have more dexterous ring
     fingers than average. This would have been difficult for me to
     know at the time, since no layouts that I had known of at the
     time had really pushed the limits on the ring
     fingers. Regardless, this was my biggest oversight with Semimak.

***** 'r and 'll
      This is one of the more specific egregious problems with
      Semimak. Words like =you're=, =you'll=, and =I'll= are abyssmal
      on the layout because they include bad SFBs on the left ring
      finger. Though they can pretty easily be alt-fingered, I still
      found them quite problematic. Because of this, I created my own
      mod, *Semimak JQ* about 2 months after its original release.

      #+begin_layoutblock
      f l h v z  ' w u o y
      
      s r n t k  c d e a i
      
      x j b m q  p g , . /
      #+end_layoutblock

      It only makes two swaps, a 3 key cycle, so it is quite easy to
      learn from the original layout. After about a month of using it
      full-time, I can confidently say that it's pretty much
      objectively better than the reference layout, at least for me.

** Successes
   By the end of the one month tournament, over 5 people had gotten above 100
   wpm with the layout on a very difficult typing test - top 10k English words,
   random punctuation, and 2 minutes. This is really impressive!
    
   However, the more interesting thing is to watch their handcams
   (for example, [[https://youtu.be/Hu1whMOKR2M?t=34][Octahedron]]'s); the fingers look just as low movement
   as the layout set out to be. This is a great success, because it
   validates my theory of finger movement. This feels accurate for me
   as well, even at over 160 wpm on Semimak, my fingers feel like
   they are moving very slowly, especially when compared to other alt
   layouts.

   Today, there are still quite a few using Semimak, several of which
   can type over 160 wpm on a basic 60 second test. For the people
   who Semimak works for, it seems to work really well.

** Takeaways
   Overall, Semimak was a very novel layout. It was the first of its
   kind[fn:1], and because of that was extremely different from most
   layouts at the time, and was overall a risky move.

   Semimak did have its shortcomings, and it isn't for everyone. But I
   think it's fair enough to say that it did spark a new paradigm for
   new layouts to be made in the style of. The design behind Semimak
   has been an inspiration for many new layouts created since.

   So, though I don't think that everyone should learn Semimak, it is
   100% a great success to me. And I could not have done it without
   the wonderful, welcoming, and unfathomably nerdy layout community,
   who encouraged and inspired me immensely. Thank you all!
    
* Development
  I created my own analyzer, [[file:genkey/index.org][genkey]] to put my ideas into effect. At
  the time, it was only made for myself, and was difficult to
  use. However, many people have used it since then, creating their
  own layouts with it, and it has been massively improved since its
  creation. If you're interested in analyzing layouts, or creating
  your own, give it a shot!

** Finger Speed
   Most layout analyzers at the moment report an SFB percentage - how
   many times you use the same finger to hit two keys in a row. But I
   found this somewhat superficial - not all SFBs are equally bad. They
   can be heavily influenced by what finger is being used and how much
   distance is traveled in the SFB. In addition, the statistic can be
   generalized more. Why do the two keys in the bigram need to be
   concurrent to be significant?
  
** Skipgrams
   Instead of only punishing same-finger bigrams weighted by finger
   and distance, I had the idea to also punish same-finger
   skipgrams. I weighted this exponentially - separated by 0 keys
   (normal bigram) is a weight of 1, separated by 1 is half as bad,
   separated by 2 is a quarter, and so on. These weights are
   arbitrary, but they were inspired both by the experiences of both
   myself and typists much faster than me.

** Distance weighting
   I weighted the distance between keys exponentially, as I think a
   distance of 2 units is much worse than a distance of 1
   unit. Layouts like Workman and Colemak DH have shown the discomfort
   that can be cause with lateral index movement - because of this,
   lateral movement was treated worse in my analyzer.

** Finger weighting
   I used a basic script that [[https://github.com/notgate][NotGate]] wrote to test how quickly I can move
   each of my fingers. For example, to see how dexterous my middle
   finger is, I would type eded over and over on QWERTY, and see how
   fast my keys per second was. This data was then used to weight how
   bad fast distance is on each finger.

** Scoring
   The layout was scored by genkey largely with the weighted finger
   movement speed metric. There was also some reward for rolling, and
   penalty for redirects.

   However, what the generator created had an extremely high redirect
   rate, and so I swapped the columns around at the end to increase
   alternation. Though I am no alternation lover, the redirect rate
   would have really been /way/ too much.

* Download
  Downloads for Windows native and EPKL, MacOS and Linux are available
  in [[https://github.com/semilin/semimak/releases][the Github Release page]]!

* Footnotes

[fn:1]Yes, the whorf layout was technically released first, but it was
created by NotGate, and we mutually shared many ideas with each
other. The original DSFB idea was mine. In addition, Semimak was long
in development by the time that whorf was released. 
