#+TITLE: (site semi)
#+DESCRIPTION: Homepage for semi, the creator of Semimak.
#+options: toc:nil
* about
:PROPERTIES:
:ID:       4c189cab-c62a-49e9-867f-f4d10bf3f5ac
:PUBDATE:  2025-12-28 Sun 20:12
:END:
I'm a programmer who likes Rust and Common Lisp. I've done a lot of
work on keyboard layouts -- you might know me as the 'semi' in
'semimak.' Corollarily, I'm also into linguistics, especially with
respect to ancient languages (quōque latīnē loquī; καὶ Ἑλληνιστὶ
λέγω). This site will thus feature writings on those subjects among
others.
* projects
:PROPERTIES:
:ID:       31733529-af56-4ba5-aa0c-9db5a143209a
:PUBDATE:  2025-12-28 Sun 20:12
:END:
I've made a number of free and open source projects. Here is a list of
some of the more important ones.
** Keymui
:PROPERTIES:
:ID:       9b39a01e-c732-475c-9321-1ce30ea48441
:END:
[[./static/keymui.avif]]

[[https://github.com/semilin/keymui][Keymui]] is an extensible and fast layout analyzer. Notable features:
- user-defined metrics and keyboards
- combo analysis (e.g., for Taipo and Crescent)
- interactive swapping with instant metric updates
- metric heatmaps
- GUI for Windows, MacOS, and Linux written in [[https://github.com/iced-rs/iced][Iced]]

Under the hood, Keymui is powered by my high-performance Rust libraries [[https://github.com/semilin/keymeow][keymeow]] and [[https://github.com/semilin/keycat][keycat]], which you can use to make your own layout analyzers.
** [[file:genkey/index.org][genkey]]
:PROPERTIES:
:ID:       2f2a8206-36ef-4800-8286-ebb4e757ba79
:END:
genkey is a keyboard layout analyzer I wrote to make Semimak. It
pioneered analysis of same-finger skipgrams.

* contact
:PROPERTIES:
:ID:       3941f903-364c-4675-b79c-215fb9339609
:PUBDATE:  2025-12-28 Sun 20:12
:END:
- email [[mailto:semi@semilin.dev][semi@semilin.dev]]
- discord ~semilin~
# Local Variables:
# jinx-languages: "en_US la grc_GR"
# End:
