#+TITLE: semi's site
#+options: toc:nil
* about
I'm a programmer who likes Rust and Common Lisp a lot. I've done a lot
of work on keyboard layouts -- you might know me as the 'semi' in
'semimak.' Corollarily, I'm also into linguistics, especially with
respect to ancient languages (quōque latīnē loquī; καὶ Ἑλληνιστὶ
λέγω). This site will thus feature writings on those subjects among
others.
* contact
- email [[mailto:semi@semilin.dev][semi@semilin.dev]]
- discord ~semilin~
* projects
** Keymeow
Keymeow is a Rust library for layout analysis using the low-level
[[https://github.com/semilin/keycat][keycat]] library. It supports shift keys, combos, and layers, all
through extremely flexible metric definition. [[https://github.com/semilin/keymui][Keymui]] is the GUI
frontend for Keymeow.
** [[file:genkey/index.org][genkey]]
genkey is a keyboard layout analyzer I wrote to make Semimak. It
pioneered analysis of same-finger skipgrams.

# Local Variables:
# jinx-languages: "en_US la grc_GR"
# End:
